#Gestion de la homepage :
front_office_homepage:
    path:     /
    defaults: { _controller: FrontOfficeBundle:Homepage:homepage }

#Gestion des Annonces :
front_office_showAnnonces:
    path:     /showAnnonces
    defaults: { _controller: FrontOfficeBundle:Annonce:showAnnonces}

front_office_showOneAnnonce:
    path:     /showOneAnnonce/{id}
    defaults: { _controller: FrontOfficeBundle:Annonce:showOneAnnonce}

front_office_create_annonce:
    path:    /createAnnonce
    defaults: { _controller: FrontOfficeBundle:Annonce:createAnnonce}

front_office_tri_annonces:
    path:    /triAnnonces
    defaults: { _controller: FrontOfficeBundle:Annonce:triAnnonces}

#Routes des templates de la navbar :
front_office_layout_navbar:
    path:     /navbar
    defaults: { _controller : FrontOfficeBundle:Navbar:navigation}

front_office_layout_about:
    path:     /about
    defaults: { _controller: FrontOfficeBundle:Navbar:about}

front_office_layout_contact:
    path:     /contact
    defaults: { _controller: FrontOfficeBundle:Navbar:contact}

#Routes des templates du blog :
front_office_blog_showArticles:
    path:     /showArticles
    defaults: { _controller:FrontOfficeBundle:Blog:showArticles}

front_office_blog_showOneArticle:
    path:     /showOneArticle/{id}
    defaults: { _controller: FrontOfficeBundle:Blog:showOneArticle}

#Routes des templates du footer -CGU Mentions légales 
front_office_static_conditions_generales_ventes:
    path:     /conditionsGenerales
    defaults: { _controller: FrontOfficeBundle:Static:conditions}

front_office_static_mentionslegales:
    path:     /mentionsLegales
    defaults: { _controller:FrontOfficeBundle:Static:mentions}