services:
    front_office.services.mail:
        class: FrontOfficeBundle\Services\MailService
        arguments: [@mailer]

    front_office.services.basket:
        class: FrontOfficeBundle\Services\BasketService
        arguments: [@session, @doctrine.orm.default_entity_manager]
