back_office_homepage:
    path:     /homepageBackOffice
    defaults: { _controller: BackOfficeBundle:Homepage:homepage }

back-office_admin_area_create:
    path:     /createArea
    defaults: { _controller: BackOfficeBundle:Area:createArea}